# Site settings
title: Maco's Realm
email: raresmac1@gmail.com
url: https://raresmac.github.io/CK3
description: "Step into a world of medieval strategy, dynastic intrigue, and epic storytelling. Here, I share my personal adventures, detailed guides, and tips for mastering Crusader Kings 3. Whether you're a new ruler or a seasoned monarch, you'll find strategies for managing your kingdom, waging wars, and navigating the complex web of relationships that define this immersive grand strategy game."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
